# -*- coding: utf-8 -*-
"""RETO 3 FINAL

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_kydXRI2p0wMUemCYZN6qdqzqP5IYTJY
"""

import os 
horario_mantenimiento_arroz="lunes y martes 4pm"
horario_mantenimiento_maiz="miercoles y viernes 4pm"
horario_mantenimiento_algodon="jueves y sabados 3pm"

horario_regado_arroz="martes 2pm"
horario_regado_maiz="lunes 8am"
horario_regado_algodon="miercoles 10am"

horario_abono_arroz="viernes 2pm"
horario_abono_maiz="miercoles 3pm"
horario_abono_algodon="sabado 3pm"


def menu_cultivos():     #SUBMENU 1 CUANDO ESCOGEN LA OPCION 1 
  print(" 1.Cultivo de arroz \n 2.Cultivo de maiz \n 3.Cultivo de algodon \n 4.salir")

def menu_etapas():       #SUBMENU 2 CUANDO ESCOGEN LA OPCION 2
  print(" 1.Cultivo de arroz \n 2.Cultivo de maiz \n 3.Cultivo de algodon \n 4.Salir")


def menu():          #MENU PRINCIPAL
  os.system('cls')
  print("Bienvenido")

  print("1. Horario de Gestión de Cultivo")
  print("2. Etapas del Cultivo")
  print("3. Información Contable")
  print("4. Salir")

while True:   #TRABAJAMOS CON CICLO WHILE PARA QUE EL USUARIO PUEDA REGRESAR AL MENU PRINCIPAL SI DESEA ESCOGER OTRA OPCION
    # Mostramos el menu
  menu()

    # solicituamos una opción al usuario
  opcionMenu = input("inserta un numero valor >> ")

  if opcionMenu=="1":    
    while True:
      menu_cultivos()   #AQUI SE EJECUTA EL SUBMENU 1 Y SE MUESTRA EN PANTALLA
      opcion_menu_cultivos = input('digite su opcion >>')

      if opcion_menu_cultivos == "1":
        print(f'el horario de mantenimiento, regado y abono son respectivamente:{horario_mantenimiento_arroz},{horario_regado_arroz},{horario_abono_arroz}')
      elif opcion_menu_cultivos =="2":
        print(f'el horario de mantenimiento, regado y abono son respectivamente: {horario_mantenimiento_maiz},{horario_regado_maiz},{horario_abono_algodon}')
      elif opcion_menu_cultivos =="3":
        print(f'el horario de mantenimiento, regado y abono son respectivamente:{horario_mantenimiento_algodon},{horario_regado_algodon},{horario_abono_algodon}')
      elif opcion_menu_cultivos =="4":
        menu()   
        break # ----> aquí lo importante PARA SALIR DEL MENU 1 Y CERRAR EL CICLO
      else:
        print ("")
        input("No has pulsado ninguna opción correcta...\npulsa una tecla para continuar")


  elif opcionMenu == "2":
    while True:         #CICLO WHILE PARA QUE SE REPITA EL MENU 
      menu_etapas()   #SUBMENU 2 AQUI SE MUESTRA EN PANTALLA
      opcion_menu2= input("Digite el numero de su opcion a escoger  ")
      if opcion_menu2 == "1":   
        print(f'El cultivo esta en etapa de recoleccion')
      elif opcion_menu2 == "2":
        print(f'El cultivo esta en etapa de crecimiento')
      elif opcion_menu2== "3":
        print(f'El cultivo esta en etapa de siembra')
      elif opcion_menu2 == "4":
        menu()
        break      #AQUI SE CIERRA EL CICLO DEL SUBMENU 2
      else:
        print ("")         #SINO ESCOGE UN VALOR CORRECTO SE MUESTRA ESTO
        input("No has pulsado ninguna opción correcta...\npulsa una tecla para continuar")


  elif opcionMenu == "3":
    print("Gastos Y costos")

    x=5

    for x in range(1,6):   #SE USO CICLO FOR PARA QUE REPITA LA OPCION 5 VECES Y SE USARON CONDICIONALES PARA CADA MES
      if x == 1:
        medicamentos_mes1 = float(input(f'ingrese el gasto en medicamentos del mes {x} >> ' ))
        print("")
        imprevistos_mes1 = float(input(f'ingrese los gastos en imprevistos del mes {x} >> '))
        print("")
        mano_obra_mes1 = float(input(f'ingrese los gastos en mano de obra del mes {x} >> '))
        print("")
        abono_mes1= float(input(f'ingrese los gastos en abono del mes {x} >> '))
        print("")
        agua_mes1= float(input(f'ingrese los gastos en agua del mes {x} >> '))
        print("")
        mantenimiento_mes1= float(input(f'ingrese los gastos en mantenimiento del mes {x} >> '))
        print("")
      elif x == 2:
        medicamentos_mes2=float(input(f'ingrese el gasto en medicamentos del mes {x} >> ' ))
        print("")
        imprevistos_mes2=float(input(f'ingrese los gastos en imprevistos del mes {x} >> '))
        print("")
        mano_obra_mes2 = float(input(f'ingrese los gastos en mano de obra del mes {x} >>  '))
        print("")
        abono_mes2= float(input(f'ingrese los gastos en abono del mes {x} >>  '))
        print("")
        agua_mes2= float(input(f'ingrese los gastos en agua del mes {x} >>  '))
        print("")
        mantenimiento_mes2= float(input(f'ingrese los gastos en mantenimiento del mes {x} >> '))
        print("")
      elif x == 3:
        medicamentos_mes3=float(input(f'ingrese el gasto en medicamentos del mes {x} >> ' ))
        print("")
        imprevistos_mes3=float(input(f'ingrese los gastos en imprevistos del mes {x} >> '))
        print("")
        mano_obra_mes3 = float(input(f'ingrese los gastos en mano de obra del mes {x} >>  '))
        print("")
        abono_mes3= float(input(f'ingrese los gastos en abono del mes {x} >>  '))
        print("")
        agua_mes3= float(input(f'ingrese los gastos en agua del mes {x} >>  '))
        print("")
        mantenimiento_mes3= float(input(f'ingrese los gastos en mantenimiento del mes {x} >> '))
        print("")
      elif x == 4:
        medicamentos_mes4=float(input(f'ingrese el gasto en medicamentos del mes {x} >>  ' ))
        print("")
        imprevistos_mes4=float(input(f'ingrese los gastos en imprevistos del mes {x} >>  '))
        print("")
        mano_obra_mes4 = float(input(f'ingrese los gastos en mano de obra del mes {x} >> '))
        print("")
        abono_mes4= float(input(f'ingrese los gastos en abono del mes {x} >>  '))
        print("")
        agua_mes4= float(input(f'ingrese los gastos en agua del mes {x} >> '))
        print("")
        mantenimiento_mes4= float(input(f'ingrese los gastos en mantenimiento del mes {x} >> '))
        print("")
      elif x == 5:
        medicamentos_mes5=float(input(f'ingrese el gasto en medicamentos del mes {x} >> ' ))
        print("")
        imprevistos_mes5=float(input(f'ingrese los gastos en imprevistos del mes {x} >> '))
        print("")
        mano_obra_mes5 = float(input(f'ingrese los gastos en mano de obra del mes {x} >> '))
        print("")
        abono_mes5= float(input(f'ingrese los gastos en abono del mes {x} >> '))
        print("")
        agua_mes5= float(input(f'ingrese los gastos en agua del mes {x} >> '))
        print("")
        mantenimiento_mes5= float(input(f'ingrese los gastos en mantenimiento del mes {x} >> '))
        print("")

        #PRODUCCION

        kilos_recolectados = float(input("Ingrese la cantidad de kilogramos recolectados"))
        print("")
        produccion = ((kilos_recolectados)/12.5)*40000
        print(f'el recaudo en pesos del total del arroz es de {produccion}')

        #COSTOS VARIABLES POR MES Y TOTAL DE 5 MESES

        costos_variables1 = medicamentos_mes1 + imprevistos_mes1
        costos_variables2 = medicamentos_mes2 + imprevistos_mes2
        costos_variables3 = medicamentos_mes3 + imprevistos_mes3
        costos_variables4 = medicamentos_mes4 + imprevistos_mes4
        costos_variables5 = medicamentos_mes5 + imprevistos_mes5
        
        #COSTOS TOTALES DEL CULTIVO MES A MES

        costos_fijos1=mano_obra_mes1 + abono_mes1 +agua_mes1+ mantenimiento_mes1
        costo_total_mes1=costos_variables1 + costos_fijos1
        print(f'El costo total del mes 1 es {costo_total_mes1}')
        print("")
        costos_fijos2=mano_obra_mes2 + abono_mes2 +agua_mes2+ mantenimiento_mes2
        costo_total_mes2=costos_variables2 + costos_fijos2
        print(f'El costo total del mes 2 es {costo_total_mes2}')
        print("")
        costos_fijos3=mano_obra_mes3+ abono_mes3 +agua_mes3+ mantenimiento_mes3
        costo_total_mes3=costos_variables3 + costos_fijos3
        print(f'El costo total del mes 3 es {costo_total_mes3}')
        print("")
        costos_fijos4=mano_obra_mes4 + abono_mes4 +agua_mes4+ mantenimiento_mes4
        costo_total_mes4=costos_variables4 + costos_fijos4
        print(f'El costo total del mes 4 es {costo_total_mes4}')
        print("")
        costos_fijos5=mano_obra_mes5 + abono_mes5 +agua_mes5+ mantenimiento_mes5
        costo_total_mes5=costos_variables5 + costos_fijos5
        print(f'El costo total del mes 5 es {costo_total_mes5}')
        print("")

        #COSTO TOTAL DE MANO DE OBRA
        
        mano_obra_total= mano_obra_mes1 + mano_obra_mes2 + mano_obra_mes3 + mano_obra_mes4 + mano_obra_mes5
        print(f'El costo tal por mano de obra es {mano_obra_total}')
        print("")

        #MESES EN LOS QUE NO HUBO GASTO

        if costo_total_mes1 =="0":
          print("En el mes 1 no hubo gastos")
        elif costo_total_mes2 =="0":
          print("En el mes 2 no hubo gastos")
        elif costo_total_mes3 == "0":
          print("En el mes 3 no hubo gastos")
        elif costo_total_mes4 == "0":
          print("En el mes 4 no hubo gastos")
        elif costo_total_mes5 =="0":
          print("En el mes 5 no hubo gastos")
        else:
          print("hubo gasto en todos los meses")
        print("")

        #Meses en los cuales el gasto fue menor a 100.000

        if costos_variables1 < 100000:
          print("El gasto del mes 1 fue menor a 100000")
        elif costos_variables2 < 100000:
          print("El gasto del mes 2 fue menor a 100000")
        elif costos_variables3 < 100000:
          print("El gasto del mes 3 fue menor a 100000")
        elif costos_variables4 < 100000:
          print("El gasto del mes 4 fue menor a 100000")
        elif costos_variables5 < 100000:
          print("El gasto del mes 5 fue menor a 100000")
        else:
          print("Los gastos fueron mayor a 100000")
        print("")

          #el costo total del mes fue mayor al gasto total del mes

        if costos_variables1 < costos_fijos1:
          print("el costo total del mes1 fue mayor al gasto total del mes 1")
        elif costos_variables2 < costos_fijos2:
          print("el costo total del mes2 fue mayor al gasto total del mes 2")
        elif costos_variables3 < costos_fijos3:
          print("el costo total del mes3 fue mayor al gasto total del mes 3 ")
        elif costos_variables4 < costos_fijos4:
          print("el costo total del mes4 fue mayor al gasto total del mes4")
        elif costos_variables5 < costos_fijos5:
          print("el costo total del mes5 fue mayor al gasto total del mes 5")
        else:
          print("los gastos fueron mayor en todos los meses")
        print("")
        print("")
         
        #VALOR PROMEDIO 

        costosvariablestotal= costos_variables1 + costos_variables2 + costos_variables3 + costos_variables4 + costos_variables5
        costosfijostotal=costos_fijos1 + costos_fijos2 + costos_fijos3 + costos_fijos4 + costos_fijos5
        valor_promedio=(costosvariablestotal + costosfijostotal)/2

        print(f'el valor promedio de costos Fijos y costos variables es de {valor_promedio}')

        #AQUI SE CALCULA SI HUBO GANANCIA 

        gasto_total=costosvariablestotal + costosfijostotal
        ganancia= produccion - gasto_total
        perdida = gasto_total - produccion
        if gasto_total < produccion:
          print(f'Hubo ganancia y fue de {ganancia}' )
        else:
          print(f'No hubo ganancia y la perdida fue de {perdida}')    

  elif opcionMenu == "4":
    break               #AQUI CERRAMOS EL WHILE INICIAL PARA SALIR DEL PROGRAMA
  else:
    print("")
    input("No has pulsado ninguna opción correcta...\npulsa una tecla para continuar")